name: Update Counter
on:
  schedule:
    - cron: '0 23 * * *' # Tous les jours à 23h
  workflow_dispatch: # Déclenchement manuel

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compter les nouvelles adhésions
        run: |
          # Script pour compter les nouveaux membres
          NEW_MEMBERS=$(curl -s "https://api.github.com/repos/votreuser/le-pain-sacre/issues?labels=adhesion" | jq '. | length')
          echo "Nouveaux membres: $NEW_MEMBERS"
          # Mettre à jour data.json (exemple simplifié)
          echo '{"total":'$(( $(curl -s https://votresite.com/data.json | jq '.total') + $NEW_MEMBERS ))'}' > data.json
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Bot"
          git add data.json
          git commit -m "Mise à jour automatique du compteur"
          git push
