name: Update Counter
on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Update counter
        run: |
          node scripts/update-counter.js
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
